### PR TITLE
Fixed sequence of linebreaks in text

### PR DESCRIPTION
**Pull request by erikhaandrikman**

### CODE REVIEW

**Comment by raulmelo-wm** [comment]
Is there any thoughts about this PR?

**Comment by g-zachar** [comment]
The change is not backwards compatible and the implementation can still be improved.

**Comment by raulmelo-wm** [comment]
Gotcha. Thanks for the feedback @g-zachar .

Is it a proper fix for that in your roadmap?

**Comment by g-zachar** [comment]
Hi @raulmelo-wm,

We're still figuring out how to address it.

Best regards

**Review by g-zachar — APPROVED** [review]

**Pull request merged**
