### PR TITLE
BD-899:Relicense Lightning to Metrological Apache

### PR DESCRIPTION
**Pull request by mallikarjuna54**

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Mallikarjuna,
Please update the branch.
Meantime, there are a few RDK headers left:
	examples/shaders/magnifier/magnifier.html
	examples/touch/Touch.js (needs a header)
	src/renderer/webgl/shaders/MagnifierShader.mjs
	tests/template/test.template.js

We have not usually changed html or mjs files but these two need the update.
Thanks

**Comment by mhughesacn** [comment]
Thanks Mallikarjuna - all good.  Still need to update branch.

**Review by g-zachar — APPROVED** [review]

**Comment by g-zachar** [comment]
Can be merged at any moment afaik.

**Comment by pradeeptakdas** [comment]
Hi @wouterlucas , 
Can you please merge this PR?

**Pull request merged**
