### PR TITLE
Integrate Vite and Vitest. Add test for TextTextureRendererUtils.

### PR DESCRIPTION
**Pull request by frank-weindel**
This PR is a shot at upgrading our build system to use [Vite](https://vitejs.dev/) (which uses rollup under the covers for production builds). I've attempted to replicate everything we have currently with rollup. The regular rollup build system remains untouched under the `build` npm command.

One of the benefits, and biggest motivator (for me), of switching to the Vite ecosystem is that we can take advantage of [Vitest](https://vitest.dev/) for unit testing. I've added that as well here along with a working test for the utility method created in rdkcentral/Lightning#442.

To build, simply run:
```
npm run build-vite
```
which will build all of the bundles necessary in parallel using another NPM package called [concurrently](https://www.npmjs.com/package/concurrently).

To run tests, run:
```
npm test
```

Vitest also integrates with Visual Studio Code via a plugin with the same name. And it's really nifty.

**Still to be done/worked out:**
- [x] Add lightning-inspect ES5 build
- [x] Get the copyright header plugin (rollup-plugin-license) to work
  - _Now using a custom Vite plugin which was very simple to write_
- [x] Verify that the bundles generated work as well as the pure rollup ones did.
- [x] Move this PR to the rdkcentral/Lightning (once rdkcentral/Lightning#442 is merged)
- [x] Remove vanilla rollup system (and have vite output to `dist`)
- [x] Configure TypeScript definitions to be moved to `dist` folder

### CODE REVIEW

**Comment by frank-weindel** [comment]
Just rebased and moved this PR over from my fork

**Comment by frank-weindel** [comment]
This is pretty much ready for review! I've tested the build outputs of this in sample projects that utilize the `lng` CLI, Webpack and Vite. Both TypeScript and plain JavaScript. All projects build just fine. Could use another set of eyes and a sanity test before release.

**Comment by frank-weindel** [comment]
> Awesome! Does this change the output generated with the `Lightning-CLI` or is this just local to the Lightning repo build? Reason I'm asking is to see if we should check whether or not our build bundles break anything downstream with the Metrological CLI and their ability to upload it to the dashboard (and if it does, adjust accordingly).

It shouldn't. This should be building compatible bundles that are expected by Lightning-CLI. I've tested it in both a JavaScript and TypeScript project created with `lng create`. Both `lng build` and `lng dev` work as expected. I'm not sure what beyond that I'd need to look out for with regards to the Metro app store/etc.

**Comment by wouterlucas** [comment]
> > Awesome! Does this change the output generated with the `Lightning-CLI` or is this just local to the Lightning repo build? Reason I'm asking is to see if we should check whether or not our build bundles break anything downstream with the Metrological CLI and their ability to upload it to the dashboard (and if it does, adjust accordingly).
> 
> It shouldn't. This should be building compatible bundles that are expected by Lightning-CLI. I've tested it in both a JavaScript and TypeScript project created with `lng create`. Both `lng build` and `lng dev` work as expected. I'm not sure what beyond that I'd need to look out for with regards to the Metro app store/etc.

OK. I guess we should submit an app and see it if works on Metro and give @robbertvancaem a headsup :)

**Review by wouterlucas — APPROVED** [review]
LGTM

**Pull request merged**
